### ISSUE TITLE
Views missing in various endpoints

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#29]
The endpoint ` GET /jobs/{job_id}` returns data about the view. Views are also mentioned in the document "Core Concepts and API Reference". Unfortunately views are missing from other relevant endpoints:
* POST /execute
* POST /jobs
* PUT /jobs/{job_id}

**Comment by m-mohr** [comment]
I removed the views for the proof-of-concept. 

**Reminder for v1.0.0:**
I removed the following property from the job_full definition:
```
      view:
        $ref: '#/definitions/view'
```

Additionally, I removed the view definition:
```
  view:
    type: object
    description: >-
      The view defines how we look at the data (spatial extent, resolution, time
      range, etc.) for processing. It can be used to experiment with tasks and
      processes on small subdataset.
    properties:
      space:
        description: >-
          Defines spatial resolution, window, and resampling method used for
          running processes on small sub datasets
        type: object
        properties:
          srs:
            type: string
            description: >-
              Spatial reference system as proj4 string or epsg code such as
              `EPSG:3857`
          window:
            type: object
            description: >-
              boundaries of the spatial window as coordinates expressed in the
              given reference system.
            required:
              - left
              - top
              - right
              - bottom
            properties:
              left:
                type: number
              top:
                type: number
              right:
                type: number
              bottom:
                type: number
          cell_size:
            type: number
          resampling:
            type: string
            description: >-
              resampling method to use (taken from
              [GDAL](http://www.gdal.org/gdal_translate.html))
            default: nearest
            enum:
              - nearest
              - bilinear
              - cubic
              - cubicspline
              - lanczos
              - average
              - mode
        example:
          srs: 'EPSG:4326'
          window:
            left: -10.21
            top: 53.23
            right: 12.542
            bottom: 12.32
          resolution: 0.25
          resampling: nearest
      time:
        description: >-
          Defines temporal resolution, window, and resampling method used for
          running processes on small sub datasets
        type: object
        properties:
          window:
            type: object
            description: Start and end date/time in ISO 8601 format
            required:
              - start
              - end
            properties:
              start:
                type: string
                format: dateTime
              end:
                type: string
                format: dateTime
          time_step:
            type: string
            description: >-
              temporal granularity given as ISO 8601 time duration. In order to
              avoid mixing inconsistent durations such as `P1M30DT24H` only a
              single integer number with date/time component such as `P1M`,
              `P30D`, `PT24H` should be specified.
          resampling:
            type: string
            description: >-
              resampling method to use (taken from
              [GDAL](http://www.gdal.org/gdal_translate.html))
            default: nearest
            enum:
              - nearest
              - bilinear
              - cubic
              - cubicspline
              - lanczos
              - average
              - mode
        example:
          window:
            start: '2017-01-01'
            end: '2018-01-01'
          resolution: P1M
          resampling: nearest
    additionalProperties: true
```

To be added again for v1.0.0. The view definition also needs to be added to the mentioned endpoints.
